# Generated by Django 2.1.7 on 2021-05-01 22:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_user', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CommandsSequence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, unique=True, verbose_name='Task name')),
                ('commands', models.TextField(verbose_name='Task commands')),
                ('group', models.ManyToManyField(to='app_user.ServerGroup', verbose_name='Server group you want to execute')),
            ],
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('end_time', models.DateTimeField(auto_created=True, auto_now=True, verbose_name='End time')),
                ('channel', models.CharField(editable=False, max_length=100, unique=True, verbose_name='Channel name')),
                ('log', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Log name')),
                ('start_time', models.DateTimeField(auto_now_add=True, verbose_name='Start time')),
                ('is_finished', models.BooleanField(default=False, verbose_name='Is finished')),
                ('width', models.PositiveIntegerField(default=90, verbose_name='Width')),
                ('height', models.PositiveIntegerField(default=40, verbose_name='Height')),
                ('gucamole_client_id', models.CharField(blank=True, editable=False, max_length=100, verbose_name='Gucamole channel name')),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_user.Server', verbose_name='Server')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
    ]
