# Generated by Django 2.1.7 on 2021-05-01 22:44

from django.conf import settings
from django.db import migrations, models
import django.utils.timezone
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('email', models.EmailField(default='user@3s.com.tn', max_length=250, unique=True, verbose_name='Email')),
                ('type', multiselectfield.db.fields.MultiSelectField(choices=[('admin', 'Administrator'), ('user', 'Privileged user'), ('auditor', 'Auditor')], default='user', max_length=18, verbose_name='Type')),
                ('first_name', models.CharField(blank=True, max_length=50, verbose_name='Firstname')),
                ('last_name', models.CharField(blank=True, max_length=50, verbose_name='Lastname')),
                ('Phone', models.CharField(max_length=12, verbose_name='Phone')),
                ('username', models.CharField(max_length=50, verbose_name='username')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date joined')),
                ('last_login', models.DateTimeField(auto_now=True, verbose_name='Last Acess')),
                ('image', models.ImageField(blank=True, default='app_manager/default.PNG', null=True, upload_to='app_manager', verbose_name='Profile picture')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
                ('staff', models.BooleanField(default=False, verbose_name='Staff')),
                ('admin', models.BooleanField(default=False, verbose_name='Admin')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updatedatetime', models.DateTimeField(auto_created=True, auto_now=True, verbose_name='Update time')),
                ('name', models.CharField(max_length=40, unique=True, verbose_name='User group name')),
                ('createdatetime', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Create time')),
                ('user', models.ManyToManyField(related_name='users', to=settings.AUTH_USER_MODEL, verbose_name='users')),
            ],
        ),
    ]
