# Generated by Django 2.1.7 on 2021-05-02 22:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_manager', '0002_auto_20210502_0215'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='code',
            name='user',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='user_permissions',
        ),
        migrations.DeleteModel(
            name='Code',
        ),
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
