# Generated by Django 2.1.7 on 2021-05-01 22:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Credential',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, unique=True, verbose_name='Credential name')),
                ('port', models.PositiveIntegerField(default=22, verbose_name='Port Number')),
                ('method', models.CharField(choices=[('password', 'password'), ('key', 'key')], default='password', max_length=40, verbose_name='Method')),
                ('key', models.TextField(blank=True, verbose_name='Key')),
                ('password', models.CharField(blank=True, max_length=40, verbose_name='Password')),
                ('proxy', models.BooleanField(default=False, verbose_name='Proxy')),
                ('proxyserverip', models.GenericIPAddressField(blank=True, null=True, protocol='ipv4', verbose_name='Proxy ip')),
                ('proxyport', models.PositiveIntegerField(blank=True, null=True, verbose_name='Proxy port')),
                ('proxypassword', models.CharField(blank=True, max_length=40, verbose_name='Proxy password')),
                ('protocol', models.CharField(choices=[('ssh-password', 'ssh-password'), ('ssh-key', 'ssh-key'), ('vnc', 'vnc'), ('rdp', 'rdp'), ('telnet', 'telnet')], default='ssh-password', max_length=40, verbose_name='Protocol')),
                ('width', models.PositiveIntegerField(default=1024, verbose_name='width')),
                ('height', models.PositiveIntegerField(default=768, verbose_name='height')),
                ('dpi', models.PositiveIntegerField(default=96, verbose_name='dpi')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Authorised User')),
            ],
        ),
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updatedatetime', models.DateTimeField(auto_created=True, auto_now=True, verbose_name='Date Updated')),
                ('name', models.CharField(default='Server name', max_length=50, unique=True, verbose_name='Server name')),
                ('hostname', models.CharField(default='hostname', max_length=40, verbose_name='Host name')),
                ('ip', models.GenericIPAddressField(protocol='ipv4', verbose_name='IP address')),
                ('createdatetime', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date created')),
                ('credential', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_user.Credential', verbose_name='Credentials')),
            ],
        ),
        migrations.CreateModel(
            name='ServerGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updatedatetime', models.DateTimeField(auto_created=True, auto_now=True, verbose_name='Update time')),
                ('name', models.CharField(max_length=40, unique=True, verbose_name='Server group name')),
                ('createdatetime', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Create time')),
                ('servers', models.ManyToManyField(related_name='servers', to='app_user.Server', verbose_name='Servers')),
            ],
        ),
    ]
